### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by pronebird** [hickory-dns/hickory-dns#3881]
**Describe the bug**

After updating from v0.26.1 to v0.26.2, hickory no longer builds:

```
    Checking hickory-resolver v0.26.2
error[E0432]: unresolved import `crate::net::tls::tls_exchange_with_bind_addr`
  --> /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hickory-resolver-0.26.2/src/connection_provider.rs:35:56
   |
35 | use crate::net::tls::{client_config, default_provider, tls_exchange_with_bind_addr};
   |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `tls_exchange_with_bind_addr` in `tls`

error[E0599]: no method named `is_connection_closed` found for enum `NetError` in the current scope
   --> /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hickory-resolver-0.26.2/src/name_server.rs:209:34
    |
209 |                         && error.is_connection_closed()
    |                                  ^^^^^^^^^^^^^^^^^^^^ method not found in `NetError`

error[E0599]: no variant, associated function, or constant named `Truncated` found for enum `NetError` in the current scope
   --> /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hickory-resolver-0.26.2/src/name_server_pool.rs:386:35
    |
386 |                         NetError::Truncated
    |                                   ^^^^^^^^^ variant, associated function, or constant not found in `NetError`

error[E0599]: no variant, associated function, or constant named `Truncated` found for enum `NetError` in the current scope
   --> /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hickory-resolver-0.26.2/src/name_server_pool.rs:391:41
    |
391 |                         err = NetError::Truncated;
    |                                         ^^^^^^^^^ variant, associated function, or constant not found in `NetError`

error[E0599]: no method named `request_timeout` found for struct `HttpsClientStreamBuilder<P>` in the current scope
   --> /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hickory-resolver-0.26.2/src/connection_provider.rs:131:25
    |
131 |                 builder.request_timeout(cx.options.timeout);
    |                         ^^^^^^^^^^^^^^^ method not found in `HttpsClientStreamBuilder<P>`

error[E0599]: no method named `request_timeout` found for struct `QuicClientStreamBuilder` in the current scope
   --> /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hickory-resolver-0.26.2/src/connection_provider.rs:152:26
    |
150 | /                     QuicClientStream::builder()
151 | |                         .crypto_config(cx.tls.clone())
152 | |                         .request_timeout(cx.options.timeout)
    | |                         -^^^^^^^^^^^^^^^ method not found in `QuicClientStreamBuilder`
    | |_________________________|
    |

error[E0599]: no method named `request_timeout` found for struct `H3ClientStreamBuilder` in the current scope
   --> /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hickory-resolver-0.26.2/src/connection_provider.rs:179:26
    |
176 | /                     H3ClientStream::builder()
177 | |                         .crypto_config(cx.tls.clone())
178 | |                         .disable_grease(*disable_grease)
179 | |                         .request_timeout(cx.options.timeout)
    | |                         -^^^^^^^^^^^^^^^ method not found in `H3ClientStreamBuilder`
    | |_________________________|
    |

error[E0599]: no variant named `ForeignClassRecord` found for enum `NetError`
   --> /Users/pronebird/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/hickory-resolver-0.26.2/src/name_server_pool.rs:216:38
    |
216 |                 return Err(NetError::ForeignClassRecord {
    |                                      ^^^^^^^^^^^^^^^^^^ variant not found in `NetError`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `hickory-resolver` (lib) due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
```

**To Reproduce**

**Expected behavior**

**System:**
 - OS: [e.g. macOS]
 - Architecture: [e.g. x86_64]
 - rustc version: [e.g. 1.28]

**Version:**
Crate: [e.g. client, server, resolver]
Version: [e.g. 0.9.1]

**Additional context**

**Comment by djc** [comment]
What is the exact command you're using to build it?

**Comment by pronebird** [comment]
`cargo check` in my project workspace

**Comment by djc** [comment]
Okay, so what features do you have enabled for various hickory crates?

**Comment by divergentdave** [comment]
The `Truncated` error makes me think the issue is that the minimum dependency version of `hickory-resolver@0.26.2` on `hickory-net@0.26.0` is incorrect, as we only just introduced `NetError::Truncated`.

**Comment by djc** [comment]
Yup, that sounds plausible.

**Comment by jmwample** [comment]
I am seeing these same errors after updating the hickory dependencies.

```
cargo update -p hickory-resolver -p hickory-proto
    Updating crates.io index
     Locking 2 packages to latest compatible versions
    Updating hickory-proto v0.26.1 -> v0.26.2
    Updating hickory-resolver v0.26.1 -> v0.26.2
note: pass `--verbose` to see 300 unchanged dependencies behind latest
```

Based on this thread I checked the `hickory-net` version and it is still at `0.26.1`. Updating that dependency resolves the compile errors and the crate compiles properly. 

```
cargo update -p hickory-net
```

Usage w/ features (after manually updating version in `Cargo.toml`)
```toml
# workspace
hickory-proto = { version = "0.26.2", default-features = false }
hickory-resolver = "0.26.2"

# crate
hickory-proto = { workspace = true }
hickory-resolver = { workspace = true, features = ["https-ring", "tls-ring", "webpki-roots"] }
```

**Comment by djc** [comment]
Should be addressed in 0.26.3 via

- https://github.com/hickory-dns/hickory-dns/pull/3895
