### ISSUE TITLE
`hickory-server` `+dnssec-ring` does not build with Rust 1.79

### ISSUE THREAD

**Issue by japaric** [hickory-dns/hickory-dns#2422]
**Describe the bug**
What the title says. As I understand, the current MSRV is 1.70 as [per CI](https://github.com/hickory-dns/hickory-dns/blob/9ad0cf2590ee6fd5a2ac0237fa417b9b30555bea/.github/workflows/test.yml#L127).

**To Reproduce**

``` console
$ cargo +1.79.0 build -p hickory-server --features dnssec-ring
(..)
error[E0277]: the trait bound `[u8]: Default` is not satisfied
   --> crates/server/src/config/dnssec.rs:262:9
    |
262 |         /// The salt used for hashing.
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `[u8]`, which is required by `Arc<[u8]>: Default`
    |
    = help: the following other types implement trait `Default`:
              &[T]
              &mut [T]
              [T; 0]
              [T; 10]
              [T; 11]
              [T; 12]
              [T; 13]
              [T; 14]
            and 27 others
    = note: required for `Arc<[u8]>` to implement `Default`

```

**Expected behavior**
The code should compile with that toolchain version.

**System:**
 - OS: Ubuntu
 - Architecture: x86_64
 - Version 22.04
 - rustc version: 1.79.0

**Version:**
Crate: `hickory-server`
Version: 9ad0cf2590ee6fd5a2ac0237fa417b9b30555bea

**Comment by djc** [comment]
I think it is still reasonable to exclude some dependencies from our MSRV jobs, although I agree that it might be better to include some/most of them. I made a proposal to handle this differently in https://github.com/hickory-dns/hickory-dns/pull/2028, but IIRC @bluejekyll wasn't a fan.

**Comment by bluejekyll** [comment]
Is this still an issue with all the cleanup in this area, @djc?

**Comment by djc** [comment]
We don't run MSRV jobs with most of our features, so there could still be regressions in older toolchain support for some of our optional features.

**Comment by djc** [comment]
We don't run MSRV jobs with most of our features, so there could still be regressions in older toolchain support for some of our optional features.
